// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AnimeInformation struct {
	AnimeID      string              `json:"animeID"`
	Title        string              `json:"title"`
	ImageURL     bool                `json:"imageURL"`
	RelatedAnime []*AnimeInformation `json:"relatedAnime"`
	RegisterUser []*User             `json:"registerUser"`
}

type AnimeRanking struct {
	AnimeInformation *AnimeInformation `json:"animeInformation"`
	Rank             int               `json:"rank"`
	User             *User             `json:"user"`
}

type NewAnimeRankingInput struct {
	Title    string `json:"title"`
	ImageURL string `json:"imageURL"`
	Rank     int    `json:"rank"`
	UserID   string `json:"userID"`
}

type User struct {
	UserID   string `json:"userID"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type UserInformationInput struct {
	Naem     string `json:"naem"`
	Password string `json:"password"`
}
