// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type AnimeRanking struct {
	AnimeID       int     `json:"animeID"`
	Title         string  `json:"title"`
	Description   *string `json:"description"`
	AnimeImageURL string  `json:"animeImageURL"`
	Rank          int     `json:"rank"`
	User          *User   `json:"user"`
}

type AuthOps struct {
	Login *LoginResponse `json:"login"`
}

type UpdateUserInput struct {
	Name        *string         `json:"name"`
	Description *string         `json:"description"`
	ProfieImage *graphql.Upload `json:"profieImage"`
}

type User struct {
	UserID         int             `json:"userID"`
	Name           string          `json:"name"`
	Password       string          `json:"password"`
	ProfieImageURL string          `json:"profieImageURL"`
	Description    *string         `json:"description"`
	HaveAnime      []*AnimeRanking `json:"haveAnime"`
}
